### ISSUE TITLE
Obvious mistakes in library

### ISSUE THREAD

**Issue by jenschr** [Seeed-Studio/Seeed_MCP9600#5]
This library is full of tests that are not tests but rather assignments since the author wrote = rather than ==. This throws "warning: suggest parentheses around assignment used as truth value" when you compile it.

If you are so unlucky as I am and use a STM32 based platform (like the hardware from Particle.io), you'll also get to rename all the generically named enums that'll conflict with the standard libraries. Would be great if the devs could look at these bugs as the library is basically useless without fixes?

**Comment by wavoigt** [comment]
Absolutly unusable :-(

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

I will solve the problem you mentioned later.

**Comment by jenschr** [comment]
Long? 5 years?

**Comment by Lesords** [comment]
I'm so sorry. I'll fix it as soon as I can.

**Comment by Lesords** [comment]
Sorry, I've been busy lately.

I didn't reproduce your problem. But I solved the problem you mentioned and updated the library version.

**Comment by Lesords** [comment]
I'm going to close this issue, feel free to re-open it if you have any other questions.
